<div align=center>
		
<p></p>
<p></p>
<font size=5>
In the Name of God
<font/>
<p></p>
 <br/>
    <br/>
    <br/>
<font color=#FF7500>
Sharif University of Technology - Departmenet of Computer Engineering
</font>
<p></p>
<font color=blue>
Machine Learning - Dr. Abbas Hosseini
</font>
<br/>
<br/>
Fall 2021

</div>

<hr/>
		<div align=center>
		    <font color=red size=6>
			    <br />
Project
            	<br/>
			</font>
<font size=4>
			<br/>
      Amin Meghrazi<br/>
      Seyed Alireza Mousavizade<br/>
      Yashar Zoroufchi Banisi
</font>
    </div>

# Libraries and Packages

In [1]:
import numpy as np
import pandas as pd 

import matplotlib.pyplot as plt
import seaborn as sns     

from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

# Loading Training Dataset

In [26]:
path = "/content/drive/MyDrive/ML_dataset/train_dataset.csv"
df = pd.read_csv(path)
df.head()

   Sale  ...                           user_id
0     0  ...  5E2C678F6586B67F61A377E1534E01FC
1     0  ...  E8247702C0DD294E0AE6B5B5E2F9E810
2     0  ...  9FD001258907F541D497040C64383696
3     0  ...  225741ACF2DBB2E5948268F5D5D352E6
4     0  ...  160A90377E54124D0BD31DB6735F0B33

[5 rows x 23 columns]

# EDA

## Getting Primarily Insight

In [27]:
df.shape

(100000, 23)

In [28]:
df.columns

Index(['Sale', 'SalesAmountInEuro', 'time_delay_for_conversion',
       'click_timestamp', 'nb_clicks_1week', 'product_price',
       'product_age_group', 'device_type', 'audience_id', 'product_gender',
       'product_brand', 'product_category(1)', 'product_category(2)',
       'product_category(3)', 'product_category(4)', 'product_category(5)',
       'product_category(6)', 'product_category(7)', 'product_country',
       'product_id', 'product_title', 'partner_id', 'user_id'],
      dtype='object')

In [29]:
df.nunique(axis = 0)

Sale                             2
SalesAmountInEuro             8932
time_delay_for_conversion     9208
click_timestamp              67045
nb_clicks_1week               1138
product_price                 4496
product_age_group                9
device_type                      4
audience_id                   3182
product_gender                  11
product_brand                 4770
product_category(1)             22
product_category(2)            145
product_category(3)            699
product_category(4)            910
product_category(5)            442
product_category(6)             89
product_category(7)              1
product_country                 17
product_id                   45447
product_title                27695
partner_id                     183
user_id                      96766
dtype: int64

In [30]:
stats = df.describe()
stats

                Sale  SalesAmountInEuro  ...  product_price  product_category(7)
count  100000.000000      100000.000000  ...  100000.000000             100000.0
mean        0.136610          15.124148  ...      10.929187                 -1.0
std         0.343437         147.248702  ...      65.574247                  0.0
min         0.000000          -1.000000  ...       0.000000                 -1.0
25%         0.000000          -1.000000  ...       0.000000                 -1.0
50%         0.000000          -1.000000  ...       0.000000                 -1.0
75%         0.000000          -1.000000  ...       0.000000                 -1.0
max         1.000000       23691.224980  ...    3928.000000                 -1.0

[8 rows x 6 columns]

## Cleaning Dataset

### Removing Redundant Variables

In [46]:
df_dropped = df.copy().drop(['product_category(7)', 'product_title', 'audience_id'], axis = 1)
df_dropped.head()

   Sale  ...                           user_id
0     0  ...  5E2C678F6586B67F61A377E1534E01FC
1     0  ...  E8247702C0DD294E0AE6B5B5E2F9E810
2     0  ...  9FD001258907F541D497040C64383696
3     0  ...  225741ACF2DBB2E5948268F5D5D352E6
4     0  ...  160A90377E54124D0BD31DB6735F0B33

[5 rows x 20 columns]

In [47]:
sold = list(df_dropped['Sale'] == 1)
drop_list = []
for feature in df_dropped.columns:
  if feature == 'Sale':
    continue
  elif feature == 'product_price' or feature == 'click_timestamp':
    not_null = list(df_dropped[feature] != 0)
    if sold == not_null:
      drop_list.append(feature)
  else:
    not_null = list(df_dropped[feature] != -1)
    if feature == 'time_delay_for_conversion':
      index = []
      for i in range(len(not_null)):
        if not_null[i] != sold[i]:
          index.append(i)
      
    if sold == not_null:
      drop_list.append(feature)
print(drop_list)
df_dropped = df_dropped.drop(drop_list, axis = 1)
#df_dropped.head()
df_dropped.loc[index]

['SalesAmountInEuro']

       Sale  ...                           user_id
781       1  ...  BD26D5724A8315EBC730B5808E287C7A
1741      1  ...  3A814799A62F803363B3BCCBC2AB58B6
2537      1  ...  01A9CF140675A17FA1532943279EFEB9
7065      1  ...  87EAFC027643ACB6E939C1595043BF96
7219      1  ...  D5CB34AA8FC349DBD985306AA3A2A2FC
8229      1  ...  CCCE4D4E01C46F00DFC2FE257495D477
10925     1  ...  54F947D21FD44FB0D5AE4CCEEE7369E3
11046     1  ...  AA7CE1394403EB221D6B05C79DC237BA
11620     1  ...  BEE1370A438BD8186D691BD5C3202CD6
16018     1  ...  FB8F64087C514C65CC7142387A2A42EB
23757     1  ...  91652E39CCA84C1A7B782A129FF7960C
24259     1  ...  0446AC710736118FBB213D062EA9E66F
24418     1  ...  F491F95ACFACF144D7E9948A114924C2
24885     1  ...  EB544708BF9C46121E8B6BEBA72F0B89
25085     1  ...  5ED7DCA64FED28677F51A64A4FB8CCE4
25927     1  ...  CACF40F0BE2FE6A29D8C2DA21AA8F98C
27232     1  ...  BA05CDD989C23D229A3CACCDEF217211
32061     1  ...  D7E3BD47D4A3EDA0637F2BC91999D195
35920     1  ...  0DC992FA71C583A3150A36296BDC188E
38791     1  ...  FF1F1DA8A95A21E72500B44D83A760B6
40672     1  ...  8313B55C06BDB6FAEB0601B46C84C034
41524     1  ...  DA75D6E70655F6554A6C8A3B95705D62
43578     1  ...  44AFB24D55CC154B04691EC42F3BA6E5
44877     1  ...  2A00AA66FA808095B9132ACE29BAEB32
45718     1  ...  B3E2325DB9CB4383BC39C98CCBA69AC9
45919     1  ...  58E514D4BC5128C0A7C4FE29A5EC6C6F
51495     1  ...  4FF524D1D46E9A396F9574D783DDA44E
51721     1  ...  A6BC07A2E9BD0C90C65FBC5A0328FE6D
56108     1  ...  0DA4C0F27D9AE67BDAF73C3EFD52E0BD
56180     1  ...  EEFB0A15EEAB164EF2DF0947DD465562
56234     1  ...  24874A10895AAB5ABFC1D58F7E0DB7DC
59045     1  ...  B1F99A8637C840D61DFD89771609701B
60390     1  ...  6D191D842A674BE6957DF8CC069C06AF
62198     1  ...  FBD7AC02A581C1F13B5AB738CDE29902
64416     1  ...  CBC766B78DACE5DEB909CF2234839C0F
64510     1  ...  A0ACF41E600446CD8D2026183E98AF13
66307     1  ...  1B1E273F85A87A3BA09E4E8EECD1CA41
66947     1  ...  2F07C33DAB239AF5CCC316C5F6A732AB
67209     1  ...  4838BF9EF8E3C362C810B2FDF1736324
70296     1  ...  482E6E9E4444A5265EB425DA69787954
70390     1  ...  712AED325572DAB3D98DF59D455C7E13
73778     1  ...  B7A62354DBF2026EBF0CE4961CEF1E51
76828     1  ...  04009A7555170B6B74B7F4947078C8F4
80710     1  ...  1988757192B3C9622605C4042E2FA643
80817     1  ...  FE03E0ED8F7656EC8BEECCB7811781D0
82772     1  ...  0FCEADB692299A07E8024D42BB460146
83531     1  ...  B4D58A1C58851078112A10245F240886
85320     1  ...  96EF3CD6674855E9277E39D6F5E2FFDA
94263     1  ...  7F74D5C9E14A8F6B6B1B791A2689105F
95793     1  ...  BE2DC05A7033BED4A8BA30BF8637C7CF
96333     1  ...  BAB2ABAE81BB47D13BF586639C269688
96918     1  ...  384ACB5AF66E006A7DB9BFE8D40B17B8
97144     1  ...  23BAD39DD8620D6F0B93E236EC1ED125
97579     1  ...  8DA929A412FC5DCD12A0864BFF992019
99136     1  ...  1A25AEB186F23EB984D57CF02F38852A

[55 rows x 19 columns]

In [53]:
# Conflict in Doc and Dataset
# There are clicks that have Sale = 1 but their time_delay_for_conversion	is -1
# So we assume that data in rows = index which is shown above, have
# inconsistent value for their time_delay_for_conversion field.
# Finally we drop this feature according to definition in the Doc.
df_dropped = df_dropped.drop('time_delay_for_conversion', axis = 1)
df_dropped.head()

   Sale  ...                           user_id
0     0  ...  5E2C678F6586B67F61A377E1534E01FC
1     0  ...  E8247702C0DD294E0AE6B5B5E2F9E810
2     0  ...  9FD001258907F541D497040C64383696
3     0  ...  225741ACF2DBB2E5948268F5D5D352E6
4     0  ...  160A90377E54124D0BD31DB6735F0B33

[5 rows x 18 columns]

### Extracting Data

In [54]:
df_dropped['click_timestamp'] = pd.to_datetime(df_dropped['click_timestamp'])
df_dropped['day'] = df_dropped['click_timestamp'].dt.day
df_dropped['hour'] = df_dropped['click_timestamp'].dt.hour
df_dropped = df_dropped.drop('click_timestamp', axis = 1)
df_dropped.head()

   Sale  nb_clicks_1week  ...  day hour
0     0               -1  ...    4    4
1     0               -1  ...    4    1
2     0               -1  ...    4   16
3     0               -1  ...    3   20
4     0             1064  ...    3   20

[5 rows x 19 columns]